title: Diego Fernandez page.
description: Web to show my professional development and my work

remote_theme: pages-themes/hacker@v0.2.0 # https://github.com/pages-themes/hacker
plugins:
- jekyll-remote-theme
