name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Caching
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
      - name: install dependencies
        run: python -m pip install -r requirements.txt
      - name: install external material
        run: git clone https://github.com/squidfunk/mkdocs-material.git
      - name: Deploy documentation
        run: mkdocs gh-deploy --force